#!/bin/bash
# Tests for the parts of omarchy-workspaces that are pure: argument parsing,
# the config transforms, and the shape of the Lua that comes out. Anything
# needing a live Hyprland is `doctor`'s job, not this file's.
#
# Run: ./test.sh

set -uo pipefail
CLI="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/bin/omarchy-workspaces"
WORK=$(mktemp -d); trap 'rm -rf "$WORK"' EXIT
PASS=0; FAIL=0

ok()   { PASS=$((PASS+1)); printf '  ✓ %s\n' "$1"; }
clip() { local t=${1//$'\n'/ }; (( ${#t} > 120 )) && printf '%s…' "${t:0:120}" || printf '%s' "$t"; }
no()   { FAIL=$((FAIL+1)); printf '  ✗ %s\n     want: %s\n     got:  %s\n' "$1" "$(clip "$3")" "$(clip "$2")" >&2; }
is()   { [[ $2 == "$3" ]] && ok "$1" || no "$1" "$2" "$3"; }
has()  { [[ $2 == *"$3"* ]] && ok "$1" || no "$1" "contains: $3" "$2"; }
hasnt(){ [[ $2 != *"$3"* ]] && ok "$1" || no "$1" "must not contain: $3" "$2"; }

# A fixed two-monitor config, so nothing depends on the machine running this.
seed() {
  cat >"$WORK/ws.json" <<'JSON'
{ "version": 1, "persistent": true,
  "monitors": { "desc:Left Panel L1": [1,2,3], "desc:Right Panel R1": [4,5] } }
JSON
}
b64() { printf '%s' "$1" | base64 -w0; }
run() { OMARCHY_WORKSPACES_CONFIG="$WORK/ws.json" OMARCHY_WORKSPACES_LUA="$WORK/ws.lua" bash "$CLI" "$@" 2>&1; }
cfg() { jq -c "$1" "$WORK/ws.json"; }

echo "expand_range"
seed
is "a range"          "$(run disable 2-4 >/dev/null; cfg '.disabled')" '[2,3,4]'
seed
is "a comma list"     "$(run disable 1,3 >/dev/null; cfg '.disabled')" '[1,3]'
seed
is "0 means ten"      "$(run disable 0 >/dev/null;   cfg '.disabled')" '[10]'
seed
is "duplicates fold"  "$(run disable 2,2,2 >/dev/null; cfg '.disabled')" '[2]'
seed
has "a bad range is refused" "$(run disable 5-1)" "bad range"
has "a word is refused"      "$(run disable seven)" "not a workspace number"

echo
echo "enable / disable round trip"
seed
run disable 2,3 >/dev/null; run enable 2 >/dev/null
is "enable removes just one"       "$(cfg '.disabled')" '[3]'
run enable 3 >/dev/null
is "the key goes when the last does" "$(cfg '. | has("disabled")')" 'false'

echo
echo "set-layout"
seed
run set-layout --base64 "$(b64 '{"L":[1,2],"R":[3,4,5]}')" --disabled-base64 "$(b64 '[5]')" >/dev/null
is "disabled is stored"            "$(cfg '.disabled')" '[5]'
is "an unknown name is kept as-is" "$(cfg '.monitors | keys | map(select(test("^desc:") | not))')" '["L","R"]'
is "untouched monitors survive"    "$(cfg '.monitors["desc:Right Panel R1"]')" '[4,5]'
seed
run set-layout --base64 "$(b64 '{"L":[1]}')" >/dev/null
is "no --disabled-base64 leaves it alone" "$(cfg '. | has("disabled")')" 'false'
has "a non-array disabled is refused" \
  "$(run set-layout --base64 "$(b64 '{"L":[1]}')" --disabled-base64 "$(b64 '{"a":1}')")" \
  "not a JSON array"
has "a non-object layout is refused" "$(run set-layout --base64 "$(b64 '[1,2]')")" "not a JSON object"

echo
echo "layout is handed back to Omarchy, not kept"
STATE="$WORK/state"
hand() { rm -rf "$STATE"; mkdir -p "$STATE"
  OMARCHY_WORKSPACES_CONFIG="$WORK/ws.json" OMARCHY_WORKSPACE_LAYOUTS="$STATE" \
    bash "$CLI" list >/dev/null 2>&1; }
printf '%s' '{"version":1,"monitors":{"A":[1,2]},"layouts":{"2":"scrolling"}}' >"$WORK/ws.json"
hand
is "the key leaves the config"     "$(cfg '. | has("layouts")')" 'false'
is "and lands where SUPER+L looks" "$(cat "$STATE/2.lua" 2>/dev/null)" \
  'hl.workspace_rule({ workspace = "2", layout = "scrolling" })'
printf '%s' '{"version":1,"profiles":[{"name":"d","monitors":{"A":[1],"B":[2,3]},"scrollable":["B"]}]}' >"$WORK/ws.json"
hand
is "the old per-monitor form too"  "$(cat "$STATE/3.lua" 2>/dev/null)" \
  'hl.workspace_rule({ workspace = "3", layout = "scrolling" })'
is "and it leaves nothing behind"  "$(cfg '. | has("scrollable")')" 'false'
seed
hand
is "a clean config hands nothing"  "$(ls "$STATE" | wc -l | tr -d ' ')" '0'

echo
echo "generated lua"echo
echo "generated lua"
seed
run disable 3 >/dev/null; run generate >/dev/null
LUA=$(cat "$WORK/ws.lua")
has "carries the do-not-edit banner" "$LUA" "GENERATED BY omarchy-workspaces"
has "lists the disabled workspace"   "$LUA" 'local disabled_list = { 3 }'
has "keeps the desc: selector"       "$LUA" 'selector = "desc:Left Panel L1"'
has "re-asserts after settling"      "$LUA" "hl.timer(settle"
has "unbinds all three variants"     "$LUA" 'hl.unbind("SUPER + SHIFT + ALT + " .. code)'
hasnt "leaves SUPER+L alone"         "$LUA" 'SUPER + L'
hasnt "sets no tiling layout at all" "$LUA" 'layout ='""

if command -v luac >/dev/null; then
  luac -p "$WORK/ws.lua" 2>/dev/null && ok "is valid Lua" || no "is valid Lua" "parses" "syntax error"
else
  printf '  - skipped: luac not installed (is valid Lua)\n'
fi

echo
echo "workspace count"
rm -f "$WORK/ws.json"
OMARCHY_WORKSPACES_CONFIG="$WORK/ws.json" OMARCHY_WORKSPACES_LUA="$WORK/ws.lua" \
  bash "$CLI" detect --count=6 >/dev/null 2>&1
if [[ -f $WORK/ws.json ]]; then
  is "detect records the count"      "$(cfg '.count')" '6'
  is "and seeds exactly that many"   "$(cfg '[.monitors[][]] | length')" '6'
else
  printf '  - skipped: detect needs a live Hyprland (2 checks)\n'
fi
seed
has "a zero count is refused" \
  "$(OMARCHY_WORKSPACES_CONFIG=$WORK/none.json bash "$CLI" detect --count=0 2>&1)" "positive number"

seed
run generate >/dev/null
has "the key sweep is named, not a literal" "$(cat "$WORK/ws.lua")" "local key_slots = 10"
has "unmanaged key slots are unbound too"   "$(cat "$WORK/ws.lua")" "disabled[ws] or not mine[ws]"

echo
echo "the layout is checked on paper, before any screen"
doc() { OMARCHY_WORKSPACES_CONFIG="$WORK/ws.json" bash "$CLI" doctor 2>&1; }
printf '%s' '{"version":1,"monitors":{"A":[1,2],"B":[2,3]}}' >"$WORK/ws.json"
has "a workspace on two monitors"  "$(doc)" "workspace 2 is on two monitors"
printf '%s' '{"version":1,"monitors":{"A":[1,2]},"disabled":[7]}' >"$WORK/ws.json"
has "disabled pointing nowhere"    "$(doc)" "disabled workspace 7 is not in the layout"
seed
hasnt "a sound layout is quiet"    "$(doc)" "is on two monitors"

echo
echo "a monitor that is not there"
printf '%s' '{"version":1,"monitors":{"A":[1,2],"desc:NOT-PLUGGED-IN":[3,4]}}' >"$WORK/ws.json"
OMARCHY_WORKSPACES_CONFIG="$WORK/ws.json" OMARCHY_WORKSPACES_LUA="$WORK/ws.lua" \
  bash "$CLI" generate >/dev/null 2>&1
has "still gets a group in the Lua" "$(cat "$WORK/ws.lua")" 'selector = "desc:NOT-PLUGGED-IN"'
has "and the reflow that places it" "$(cat "$WORK/ws.lua")" "local function placement()"
has "nearest-neighbour, left first"  "$(cat "$WORK/ws.lua")" "(i > from and 1 or 0)"

echo
echo "config guards"
printf 'not json' >"$WORK/ws.json"
has "a corrupt config is refused" "$(run list)" "not a version 1 config"
printf '{"version":2,"monitors":{}}' >"$WORK/ws.json"
has "a future version is refused" "$(run list)" "not a version 1 config"

echo
echo "the overview shortcut"
# Whether the key is free is read from the files, so the test owns the files:
# its own bindings.lua, and an empty stand-in for Omarchy's defaults.
mkdir -p "$WORK/hypr" "$WORK/omarchy/default/hypr"
bind() { OMARCHY_PATH="$WORK/omarchy" OMARCHY_WORKSPACES_BINDINGS="$WORK/hypr/bindings.lua" \
  OMARCHY_WORKSPACES_STATE="$WORK/bstate" bash "$CLI" bind-overview "$@" 2>&1; }
fresh() { rm -rf "$WORK/bstate"; printf -- '-- mine\n' >"$WORK/hypr/bindings.lua"; }

fresh; bind >/dev/null
B=$(cat "$WORK/hypr/bindings.lua")
has "writes the block under the plugin's own comment" "$B" \
  "-- Workspaces (io.github.kimm-stensborg.workspaces)"
has "binds the key left of 1 by position" "$B" 'o.bind("SUPER + code:49", "Workspace overview",'
has "summons the overview, payload escaped for Lua" "$B" \
  "summon io.github.kimm-stensborg.workspaces '{\\\"view\\\":\\\"overview\\\"}'\")"
has "leaves what was there alone" "$B" "-- mine"
is "ends on a newline, so the next append gets its own line" \
  "$(tail -c1 "$WORK/hypr/bindings.lua" | od -An -c | tr -d ' ')" '\n'
bind >/dev/null
is "a second run adds nothing" "$(grep -c 'o.bind' "$WORK/hypr/bindings.lua")" '1'

# What Plugin Manager reads: the same capture it uses on bindings.lua.
PM=$(grep 'o\.bind(' "$WORK/hypr/bindings.lua" | jq -Rr '
  capture("^\\s*o\\.bind\\(\\s*\"(?<keys>[^\"]*)\"\\s*,\\s*\"(?<d>[^\"]*)\"\\s*,\\s*\"(?<c>(\\\\.|[^\"\\\\])*)\"")
  | .c | gsub("\\\\(?<x>.)"; .x)')
is "Plugin Manager reads back the real command" "$PM" \
  "omarchy-shell shell summon io.github.kimm-stensborg.workspaces '{\"view\":\"overview\"}'"

sed -i '/^-- Workspaces (/,+1d' "$WORK/hypr/bindings.lua"
bind >/dev/null
is "a removed shortcut stays removed" "$(grep -c 'o.bind' "$WORK/hypr/bindings.lua")" '0'
bind --force >/dev/null
is "--force offers it again" "$(grep -c 'o.bind' "$WORK/hypr/bindings.lua")" '1'

fresh; printf 'o.bind("SUPER + GRAVE", "Mine", "foot")\n' >>"$WORK/hypr/bindings.lua"
has "a key bound by name is not taken over" "$(bind)" "is taken"
is "and nothing is written" "$(grep -c 'overview' "$WORK/hypr/bindings.lua")" '0'
fresh; printf 'o.bind("SUPER + code:49", "Theirs", "foot")\n' >"$WORK/omarchy/default/hypr/bindings.lua"
has "nor one Omarchy binds by position" "$(bind)" "is taken"
rm -f "$WORK/omarchy/default/hypr/bindings.lua"
fresh; printf 'o.bind("SUPER + SHIFT + GRAVE", "Mine", "foot")\n' >>"$WORK/hypr/bindings.lua"
bind >/dev/null
is "SUPER + SHIFT on the same key is no conflict" "$(grep -c 'Workspace overview' "$WORK/hypr/bindings.lua")" '1'

rm -rf "$WORK/bstate" "$WORK/hypr/bindings.lua"
bind >/dev/null
is "no bindings.lua, no new file" "$([[ -e $WORK/hypr/bindings.lua ]] && echo made || echo none)" 'none'

if command -v luac >/dev/null; then
  fresh; bind >/dev/null
  luac -p "$WORK/hypr/bindings.lua" 2>/dev/null && ok "the block is valid Lua" || no "the block is valid Lua" "parses" "syntax error"
fi

echo
echo "the overview shortcut, as the editor shows it"
key() { OMARCHY_WORKSPACES_XKB_LAYOUT=$1 OMARCHY_WORKSPACES_XKB_VARIANT= \
  OMARCHY_WORKSPACES_BINDINGS="$WORK/hypr/bindings.lua" bash "$CLI" overview-key 2>&1; }
fresh; bind >/dev/null
if command -v xkbcli >/dev/null; then
  is "code:49 is ½ on a Danish keyboard" "$(key dk)" 'SUPER + ½'
  is "and \` on a US one"                "$(key us)" 'SUPER + `'
else
  printf '  - skipped: xkbcli not installed (2 checks)\n'
fi
sed -i 's/SUPER + code:49/SUPER + ALT + W/' "$WORK/hypr/bindings.lua"
is "a key moved since is read from the file" "$(key us)" 'SUPER + ALT + W'
printf -- '-- mine\n' >"$WORK/hypr/bindings.lua"
is "no shortcut, nothing printed"            "$(key us)" ''

echo
echo "presets"
# Stand-ins for Hyprland's answers, and real processes for the windows to
# belong to, so the launch recipes are read from /proc the way they are live.
mkdir -p "$WORK/proj" "$WORK/data/applications"
printf '[Desktop Entry]\nName=Writer\nExec=writer\nStartupWMClass=Writer-App\n' >"$WORK/data/applications/writer.desktop"
# Its own session, so it has no terminal: run from one, its foreground would
# otherwise be this script.
setsid bash -c 'cd "$1" && sleep 60; :' _ "$WORK/proj" & TERM_PID=$!
bash -c 'sleep 60; :' _ --app=https://mail.example/ & APP_PID=$!
sleep 0.2
cat >"$WORK/monitors.json" <<'JSON'
[ { "id": 0, "name": "A", "x": 0,    "y": 0, "width": 2560, "height": 1440, "scale": 1,
    "focused": true,  "activeWorkspace": { "id": 1 } },
  { "id": 1, "name": "B", "x": 2560, "y": 0, "width": 2560, "height": 1440, "scale": 1,
    "focused": false, "activeWorkspace": { "id": 5 } } ]
JSON
cat >"$WORK/workspaces.json" <<'JSON'
[ { "id": 1, "monitorID": 0, "monitor": "A", "tiledLayout": "dwindle" },
  { "id": 5, "monitorID": 1, "monitor": "B", "tiledLayout": "scrolling" } ]
JSON
# A Hyprland that answers nothing, so no test can reach the real one, and
# the launchers a restore checks for.
mkdir -p "$WORK/fakebin"
printf '#!/bin/sh\nexit 1\n' >"$WORK/fakebin/hyprctl"
for c in xdg-terminal-exec omarchy-launch-webapp uwsm-app; do printf '#!/bin/sh\nexit 0\n' >"$WORK/fakebin/$c"; done
chmod +x "$WORK/fakebin/"*
client() { # address class ws monitor pid floating title [x y] [tags] [stableId]
  jq -cn --arg a "$1" --arg c "$2" --argjson ws "$3" --argjson m "$4" --argjson p "$5" \
    --argjson f "$6" --arg t "$7" --argjson x "${8:-0}" --argjson y "${9:-0}" \
    --argjson tags "${10:-[]}" --arg s "${11:-1}" '
    { address: $a, class: $c, initialClass: $c, title: $t, pid: $p, stableId: $s,
      workspace: { id: $ws, name: ($ws | tostring) }, monitor: $m, floating: $f,
      at: [$x, $y], size: [800, 600], fullscreen: 0, pinned: false, hidden: false, tags: $tags }'
}
{
  client 0xa1 Writer-App 1 0 $$ false "Draft" 0 0 '[]' 3
  client 0xa2 foot 1 0 "$TERM_PID" false "shell" 0 0 '["terminal*"]' 2
  client 0xa3 Mail-App 5 1 "$APP_PID" true "Mail" 2660 150 '[]' 4
  client 0xb1 xdg-desktop-portal-gtk 1 0 $$ true "Open File"
  client 0xb2 Writer-App 1 0 $$ true "Open File"
  client 0xb3 Writer-App 1 0 $$ false "Preferences"
  client 0xb4 foot -98 0 $$ false "scratch"
  client 0xb5 Writer-App 5 1 $$ true "Choose a colour"
  client 0xb6 org.omarchy.btop 1 0 $$ true "btop" 0 0 '["terminal*"]'
} | jq -s . >"$WORK/clients.json"
pre() { OMARCHY_WORKSPACES_PRESETS="$WORK/presets.json" OMARCHY_WORKSPACES_CLIENTS="$WORK/clients.json" \
  OMARCHY_WORKSPACES_MONITORS="$WORK/monitors.json" OMARCHY_WORKSPACES_WORKSPACES="$WORK/workspaces.json" \
  XDG_DATA_HOME="$WORK/data" XDG_DATA_DIRS="$WORK/none" PATH="$WORK/fakebin:$PATH" \
  OMARCHY_WORKSPACES_STATE="$WORK/pstate" bash "$CLI" preset "$@" 2>&1; }
pcfg() { jq -c "$1" "$WORK/presets.json"; }

has "saving says what was kept" "$(pre save Work --skip '["0xb3"]')" "3 windows on 2 workspaces (5 left out)"
is "dialogs, pickers, parented, special and Omarchy TUI windows are left out" \
  "$(pcfg '.presets.Work.windows | map(.class)')" '["foot","Writer-App","Mail-App"]'
is "each workspace in the order its windows opened" "$(pcfg '.presets.Work.windows | map(.workspace)')" '[1,1,5]'
is "a floating window is kept relative to its monitor" "$(pcfg '.presets.Work.windows[2].at')" '[100,150]'
is "what was on screen, and where focus was" "$(pcfg '.presets.Work | [.focused, .shown]')" '[1,[1,5]]'
is "each workspace keeps its layout and its monitor's size" "$(pcfg '.presets.Work.workspaces')" \
  '{"1":{"layout":"dwindle","monitor":[2560,1440]},"5":{"layout":"scrolling","monitor":[2560,1440]}}'
is "a terminal keeps its directory" "$(pcfg '.presets.Work.windows[0].launch.cwd')" "\"$WORK/proj\""
is "what it runs is kept only by name when not on the rerun list" \
  "$(pcfg '.presets.Work.windows[0].launch | [.run, .skipped, has("argv")]')" '[null,"sleep 60",false]'
has "and show says it will not run again" "$(pre show Work)" "(not run again: sleep 60)"
is "an app is opened from its desktop entry" "$(pcfg '.presets.Work.windows[1].launch.argv')" '["uwsm-app","--","writer.desktop"]'
is "a web app from its own URL" "$(pcfg '.presets.Work.windows[2].launch.argv')" '["omarchy-launch-webapp","https://mail.example/"]'
is "or from its class, when the browser's process owns it" \
  "$(OMARCHY_WORKSPACES_CLIENTS= bash -c "source <(sed -n '/^webapp_url()/,/^}/p' '$CLI'); webapp_url chrome-discord.com__channels_@me-Default")" \
  'https://discord.com/channels/@me'
unpack() { bash -c "source <(sed -n '/^unpack_argv()/,/^}/p' '$CLI'); unpack_argv '$1'"; }
is "Chromium's one-string command line is split back up" \
  "$(unpack '["/usr/bin/env --flag=a  --other"]')" '["/usr/bin/env","--flag=a","--other"]'
is "but a real argument with spaces is left whole" "$(unpack '["no such file here"]')" '["no such file here"]'
is "and so is an ordinary argv" "$(unpack '["/usr/bin/env","a b"]')" '["/usr/bin/env","a b"]'
has "a list names it" "$(pre list)" "Work — 3 windows on 2 workspaces"
jq '.rerun = ["sleep"]' "$WORK/presets.json" >"$WORK/presets.tmp" && mv "$WORK/presets.tmp" "$WORK/presets.json"
pre save "  Work  " --skip '["0xb3"]' >/dev/null
is "the same name, trimmed, replaces it" "$(pcfg '.presets | keys')" '["Work"]'
is "a program added to the rerun list is kept to run again" "$(pcfg '.presets.Work.windows[0].launch.run')" '["sleep","60"]'
is "and the list survives a save" "$(pcfg '.rerun')" '["sleep"]'
pre save Home Desk >/dev/null
is "a name can have spaces and more than one word" "$(pcfg '.presets | keys')" '["Home Desk","Work"]'
has "an empty name is refused" "$(pre save '   ')" "needs a name"
has "a runaway name is refused" "$(pre save "$(printf 'x%.0s' {1..41})")" "at most 40"
has "a bad skip list is refused" "$(pre save X --skip '{}')" "JSON array"
has "an unknown preset is named" "$(pre show Nope)" "no preset called “Nope”"
pre delete "Home Desk" >/dev/null
is "delete removes just that one" "$(pcfg '.presets | keys')" '["Work"]'

# Restoring onto a desk that has one of its apps open already, on the wrong
# workspace, and another window of the same app that the preset never had.
{
  client 0xc1 Writer-App 3 0 $$ false "Other"
  client 0xc2 Writer-App 2 0 $$ false "Draft"
  client 0xc3 foot -98 0 $$ false "scratch"
} | jq -s . >"$WORK/clients.json"
PLAN=$(pre restore Work --dry-run)
has "an open window with the same title is reused" "$PLAN" "reuse  0xc2 Writer-App → 1"
hasnt "and no other window of that app is taken" "$PLAN" "0xc1"
hasnt "the scratchpad is never raided" "$PLAN" "0xc3"
has "the terminal is launched as a shell in its directory" "$PLAN" \
  "launch foot → 1: uwsm-app -- xdg-terminal-exec --app-id=foot --dir=$WORK/proj"
has "running its program again, in a shell that stays after it" "$PLAN" \
  "-e bash -c \"\$@\"; exec \"\${SHELL:-bash}\" _ sleep 60"
has "and the web app" "$PLAN" "launch Mail-App → 5: omarchy-launch-webapp https://mail.example/"
is "in the order the preset keeps" "$(grep -E '^(reuse|launch)' <<<"$PLAN" | awk '{print $2}' | tr '\n' ' ')" \
  'foot 0xc2 Mail-App '

# A browser runs all its windows from one process, started with the --app=
# of whichever web app opened it first. That URL is no other window's.
bash -c 'sleep 60; :' _ --app=https://discord.com/channels/@me & BROWSER_PID=$!
printf '[Desktop Entry]\nName=Brave\nExec=brave\nStartupWMClass=brave-browser\n' >"$WORK/data/applications/brave-browser.desktop"
{
  client 0xd1 brave-x.com__-Default 1 0 "$BROWSER_PID" false "Home / X" 0 0 '[]' 5
  client 0xd2 brave-browser 1 0 "$BROWSER_PID" false "Plugins - Brave" 0 0 '[]' 6
  client 0xd3 brave-discord.com__channels_@me-Default 1 0 "$BROWSER_PID" false "Discord" 0 0 '[]' 7
} | jq -s . >"$WORK/browser.json"
cp "$WORK/clients.json" "$WORK/desk.json"
cp "$WORK/browser.json" "$WORK/clients.json"
pre save Browser >/dev/null
is "a web app sharing the browser's process is opened from its own class" \
  "$(pcfg '.presets.Browser.windows[0].launch.argv')" '["omarchy-launch-webapp","https://x.com/"]'
is "the browser's own window from its desktop entry" \
  "$(pcfg '.presets.Browser.windows[1].launch.argv')" '["uwsm-app","--","brave-browser.desktop"]'
is "and the web app that started it from its exact URL" \
  "$(pcfg '.presets.Browser.windows[2].launch.argv')" '["omarchy-launch-webapp","https://discord.com/channels/@me"]'
kill "$BROWSER_PID" 2>/dev/null
# As an older version saved them: every window with the first web app's URL.
jq '.presets.Browser.windows |= map(.launch = { via: "webapp",
  argv: ["omarchy-launch-webapp", "https://discord.com/channels/@me"] })' "$WORK/presets.json" >"$WORK/presets.tmp" &&
  mv "$WORK/presets.tmp" "$WORK/presets.json"
echo "[]" >"$WORK/clients.json"
PLAN=$(pre restore Browser --dry-run)
has "a preset saved that way opens each web app from its class" "$PLAN" \
  "launch brave-x.com__-Default → 1: omarchy-launch-webapp https://x.com/"
has "the browser from its desktop entry" "$PLAN" "launch brave-browser → 1: uwsm-app -- brave-browser.desktop"
has "and keeps the URL that does fit" "$PLAN" \
  "launch brave-discord.com__channels_@me-Default → 1: omarchy-launch-webapp https://discord.com/channels/@me"
pre delete Browser >/dev/null
mv "$WORK/desk.json" "$WORK/clients.json"

# Only now: every save above reads its launch recipes from these processes.
kill "$TERM_PID" "$APP_PID" 2>/dev/null

# Presets written by hand: what an older version saved, and layouts to read.
win() { # class workspace floating x y w h [launch]
  local launch=${8:-}
  if [[ -z $launch ]]; then launch='{"via":"command","argv":["uwsm-app","--","true"]}'; fi
  jq -cn --arg c "$1" --argjson ws "$2" --argjson f "$3" --argjson x "$4" --argjson y "$5" \
    --argjson w "$6" --argjson h "$7" --argjson l "$launch" '
    { workspace: $ws, class: $c, title: "", floating: $f, fullscreen: 0, pinned: false,
      at: [$x, $y], size: [$w, $h], launch: $l }'
}
mkpreset() { # name workspaces-json, windows on stdin
  jq -s --arg n "$1" --argjson s "$2" '{ version: 1, presets: { ($n): { workspaces: $s, windows: . } } }' >"$WORK/presets.json"
}
echo '[]' >"$WORK/clients.json"

{
  win foot 1 false 0 0 800 600 '{"via":"terminal","cwd":"/tmp","run":["rm","-rf","x"],"argv":["uwsm-app","--","xdg-terminal-exec","--app-id=foot","--dir=/tmp","-e","rm","-rf","x"]}'
  win Editor 1 false 0 0 800 600 '{"via":"terminal","cwd":"/tmp","run":["/usr/bin/nvim","notes.md"]}'
  win org.omarchy.btop 1 true 0 0 800 600 '{"via":"terminal","argv":["uwsm-app","--","xdg-terminal-exec","--app-id=org.omarchy.btop","-e","btop"]}'
  win Gone-App 1 false 0 0 800 600 '{"via":"desktop","argv":["uwsm-app","--","gone.desktop"]}'
  win Moved-App 1 false 0 0 800 600 '{"via":"desktop","argv":["uwsm-app","--","moved.desktop"],"fallback":["uwsm-app","--","true"]}'
  win No-Way 1 false 0 0 800 600 '{"via":"none"}'
} | mkpreset Old '{}'
PLAN=$(pre restore Old --dry-run)
has "an old preset's terminal only opens a shell" "$PLAN" "launch foot → 1: uwsm-app -- xdg-terminal-exec --app-id=foot --dir=/tmp"
hasnt "and never runs a command the rerun list does not allow" "$PLAN" "rm -rf"
has "one it allows is run again" "$PLAN" "launch Editor → 1: uwsm-app -- xdg-terminal-exec --app-id=Editor --dir=/tmp -e bash -c"
has "with its arguments" "$PLAN" "_ /usr/bin/nvim notes.md"
has "an Omarchy TUI window from an old preset is dropped" "$PLAN" "gone   org.omarchy.btop"
has "an app no longer installed is dropped" "$PLAN" "gone   Gone-App"
has "one whose entry went falls back to its command line" "$PLAN" "launch Moved-App → 1: uwsm-app -- true"
has "one with no way to open it is dropped" "$PLAN" "gone   No-Way"

{
  win A 1 false 0 0 1000 1000
  win B 1 false 1010 0 490 495
  win C 1 false 1010 505 490 495
  win X 5 false 0 0 830 1000
  win Y 5 false 850 0 1250 495
  win Z 5 false 850 505 1250 495
  win F 5 true 100 100 400 300
} | mkpreset Desk '{"1":{"layout":"dwindle","monitor":[2560,1440]},"5":{"layout":"scrolling","monitor":[2560,1440]}}'
PLAN=$(pre restore Desk --dry-run)
has "dwindle is rebuilt split by split" "$PLAN" "$(printf 'arrange 1 (dwindle)\n  A#0\n  B#1 right of A#0, ratio 1.34\n  C#2 below B#1, ratio 1')"
has "scrolling column by column, sized, the stacked ones pulled in" "$PLAN" \
  "$(printf 'arrange 5 (scrolling)\n  X#3 first, width 0.333\n  Y#4 after X#3, width 0.5\n  Z#5 under Y#4')"
hasnt "a floating window is left out of the layout" "$PLAN" "  F#6"

# A real restore, with nothing to launch: one app is open already, the other
# is not installed any more and is taken out of the preset.
{
  win Writer-App 1 false 0 0 800 600 '{"via":"desktop","argv":["uwsm-app","--","writer.desktop"]}'
  win Gone-App 1 false 0 0 800 600 '{"via":"desktop","argv":["uwsm-app","--","gone.desktop"]}'
} | mkpreset Back '{}'
client 0xd1 Writer-App 1 0 $$ false "Draft" | jq -s . >"$WORK/clients.json"
OUT=$(pre restore Back)
has "a restore says how far it has got" "$OUT" "Arranging workspace 1"
has "and what it removed" "$OUT" "0 opened, 1 already open. Removed from the preset, as not installed any more: Gone-App"
is "the app that is gone is taken out of the preset" "$(pcfg '.presets.Back.windows | map(.class)')" '["Writer-App"]'

# A real restore that launches: each app puts up its window a second after
# it is started, and one never does.
cat >"$WORK/fakebin/uwsm-app" <<'SH'
#!/bin/sh
[ "$1" = -- ] && shift
case $1 in fake-app) exec "$@" ;; esac
exit 0
SH
cat >"$WORK/fakebin/fake-app" <<SH
#!/bin/bash
sleep 1
[[ \$1 == Never ]] && exit 0
exec 9>"$WORK/clients.lock"; flock 9
jq --arg c "\$1" --arg a "0x\$\$\$RANDOM" '. + [{ address: \$a, class: \$c, initialClass: \$c, title: "",
  pid: 1, workspace: { id: 9, name: "9" }, monitor: 0, floating: true, at: [0, 0], size: [10, 10],
  fullscreen: 0, pinned: false, hidden: false, tags: [] }]' "$WORK/clients.json" >"$WORK/clients.new"
mv "$WORK/clients.new" "$WORK/clients.json"
SH
chmod +x "$WORK/fakebin/"*
fake() { win "$1" "$2" false 0 0 800 600 "{\"via\":\"command\",\"argv\":[\"uwsm-app\",\"--\",\"fake-app\",\"$1\"]}"; }
{ fake P 1; fake Q 1; fake R 5; fake P 5; fake Never 5; } | mkpreset Many '{}'
echo '[]' >"$WORK/clients.json"
START=$SECONDS
OUT=$(OMARCHY_WORKSPACES_LAUNCH_TIMEOUT=2 pre restore Many)
TOOK=$((SECONDS - START))
has "every app that opens is placed" "$OUT" "4 opened, 0 already open"
has "and one that never does is named" "$OUT" "Did not open: Never"
is "the apps open side by side, two windows of one app in turn" "$((TOOK <= 3))" 1
is "each window taken once" "$(jq '[.[].address] | unique | length' "$WORK/clients.json")" 4

printf 'nope' >"$WORK/presets.json"
has "a broken presets file is refused, not overwritten" "$(pre save Again)" "not a version 1 presets file"
is "and is left as it was" "$(cat "$WORK/presets.json")" 'nope'

echo
printf '%d passed, %d failed\n' "$PASS" "$FAIL"
[[ $FAIL -eq 0 ]]
